### ISSUE TITLE
Add support for arbitrary link functions

### ISSUE THREAD

**Issue by bgroenks96** [cpfiffer/BayesModels#3]
`blm` currently supports only the identity link function for linear response variables. We should also allow the user to easily specify alternative link functions to make it a true Bayesian GLM.

There are two options here:

1. Provide pre-built implementations of common link functions and their respective distributions.
2. Allow the user to specify whatever link they want via a function F: yhat -> D, where yhat is the linear predictor and D is the response distribution.

Option 2 seems nicer but has the technical difficulty of allowing for arbitrary priors and variable names which depend on the link function and are not known ahead of time.

**Comment by just-cameron** [comment]
I think for now 1 is easier to do and probably satisfactory. 2 is nice but probably too much effort to implement.

**Comment by bgroenks96** [comment]
I think #4 strikes an pretty good balance between the two. The user can also now simply write their own model and pass it into `bayesreg` which should allow plenty of flexibility at the cost of a little bit of convenience.
